# Generated by Django 2.0.3 on 2019-08-31 00:22

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80, verbose_name='资料分类')),
            ],
        ),
        migrations.AddField(
            model_name='studylink',
            name='study_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.CharField, to='wxapi.StudyClass'),
        ),
    ]
