# Generated by Django 2.0.3 on 2019-08-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0002_auto_20190831_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyclass',
            name='num',
            field=models.IntegerField(default=0, verbose_name='资料数量'),
        ),
    ]
