# Generated by Django 2.0.3 on 2019-08-31 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0004_studyclass_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='study_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wxapi.StudyClass', verbose_name='资料类型'),
        ),
    ]
