# Generated by Django 2.0.3 on 2019-09-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0005_article_study_class'),
    ]

    operations = [

        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='customer',
            name='student_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='学号'),
        ),
    ]
