# Generated by Django 2.0.3 on 2019-09-08 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0007_errand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrandRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='接单时间')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.IntegerField(default=0, verbose_name='是否预定跑腿信息通知，已预定:1,未预定：0'),
        ),
        migrations.AlterField(
            model_name='errand',
            name='price',
            field=models.FloatField(default=0, max_length=5, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='errandrecord',
            name='errand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapi.Errand', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='errandrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxapi.Customer', verbose_name='接单者'),
        ),
    ]
