# Generated by Django 2.0.3 on 2019-09-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0008_auto_20190908_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态 1：发布， 0:删除'),
        ),
    ]
