# Generated by Django 2.0.3 on 2019-09-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0010_auto_20190909_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, verbose_name='ip')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
