# Generated by Django 2.0.3 on 2019-09-11 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0012_iprecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='study_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wxapi.StudyClass', verbose_name='资料类型：科目'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='openid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信用户唯一标识openid'),
        ),
    ]
