# Generated by Django 2.0.3 on 2019-09-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0014_auto_20190913_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='telephone',
            name='site',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='地点'),
        ),
    ]
