# Generated by Django 2.0.3 on 2019-09-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0015_telephone_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='telephone',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='名称'),
        ),
    ]
