# Generated by Django 2.0.3 on 2019-09-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0016_telephone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='号码'),
        ),
    ]
