# Generated by Django 2.0.3 on 2019-09-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0017_auto_20190915_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryphone',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态 1：有效， 0:无效'),
        ),
        migrations.AddField(
            model_name='telephone',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态 1：有效， 0:无效'),
        ),
    ]
