# Generated by Django 2.0.3 on 2019-09-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0018_auto_20190915_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='advertise',
            name='over_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到期时间'),
        ),
        migrations.AddField(
            model_name='advertise',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='advertise',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='文章权重'),
        ),
    ]
