# Generated by Django 2.0.3 on 2019-09-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0020_auto_20190922_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wxapi.Customer', verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='place',
            field=models.CharField(max_length=10, verbose_name='宣传位置'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
