# Generated by Django 2.0.3 on 2019-09-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0022_auto_20190923_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='desc',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='简述'),
        ),
    ]
