# Generated by Django 2.0.3 on 2019-09-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0023_advertise_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='place',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='宣传位置'),
        ),
    ]
