# Generated by Django 2.0.3 on 2019-09-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0024_auto_20190924_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
